# dynamic-datasource
spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: dsa
      datasource:
        dsa_1:
          username: ***
          password: ***
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dsa_1?useUnicode=true&characterEncoding=utf-8&useSSL=true
        dsa_2:
          username: ***
          password: ***
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dsa_2?useUnicode=true&characterEncoding=utf-8&useSSL=true
        dsb:
          username: ***
          password: ***
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dsb?useUnicode=true&characterEncoding=utf-8&useSSL=true

# mybatis
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml