jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: name.guolanren
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
#    otherArea:
#      type: linkedhashmap
#      limit: 100
#      keyConvertor: fastjson
#      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      readFrom: slavePreferred
      # sentinel 主备切换
#      uri: redis-sentinel://127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381/?sentinelMasterId=mymaster
      # 集群
      uri:
        - redis://127.0.0.1:6379
        - redis://127.0.0.1:6380
        - redis://127.0.0.1:6381
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      keyPrefix: 'jetcache:'
#    otherArea:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: kryo
#      valueDecoder: kryo
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${redis.host}
#      port: ${redis.port}
#      password: ***
#      sentinels: 127.0.0.1:26379 , 127.0.0.1:26380, 127.0.0.1:26381
#      masterName: mymaster