jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      readFrom: slavePreferred
      uri:
        - redis://127.0.0.1:6379
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      keyPrefix: 'jetcache:'