# dynamic-datasource
spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      datasource:
        master:
          username: guolanren
          password: hahaha
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=true
        # slave组下有两个子库slave_1,slave_2
        slave_1:
          username: guolanren
          password: hahaha
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=utf-8&useSSL=true
        slave_2:
          username: guolanren
          password: hahaha
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=utf-8&useSSL=true

# mybatis
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml